import { config } from 'dotenv';
import { DataSource } from 'typeorm';
import * as fs from 'fs';
import * as path from 'path';

config();

/**
 * Dumps the current state of every master table from the live
 * DATABASE_URL into `master-data.generated.ts`. That file then
 * becomes the canonical seed input — run `npm run seed` on any fresh
 * DB to reproduce it.
 *
 * Re-running `seed:dump` overwrites the generated file with the current
 * DB state, so it doubles as a "snapshot" tool for master data changes.
 *
 * Keep this list in sync with:
 *   - seed-master-data.ts (the hardcoded defaults)
 *   - seed-from-snapshot.ts (replay path)
 *
 * Usage:  npm run seed:dump
 */

const TABLES = [
  'master_admin_roles',
  'master_genders',
  'master_qualifications',
  'master_role_types',
  'master_leave_types',
  'master_leave_durations',
  'master_file_types',
  'master_sla_config',
  'master_notification_templates',
  'master_public_holidays',
  'master_departments',
  'master_designations',
  'master_marital_statuses',
  'master_document_types',
  'master_relations',
] as const;

type TableName = (typeof TABLES)[number];

const ORDER_BY: Record<TableName, string> = {
  master_admin_roles: 'name',
  master_genders: 'sort_order',
  master_qualifications: 'sort_order',
  master_role_types: 'sort_order',
  master_leave_types: 'sort_order',
  master_leave_durations: 'sort_order',
  master_file_types: 'context, mime_type, extension',
  master_sla_config: 'config_key',
  master_notification_templates: 'event_key',
  master_public_holidays: 'year, date',
  master_departments: 'sort_order, label',
  master_designations: 'department_id, sort_order, label',
  master_marital_statuses: 'sort_order',
  master_document_types: 'sort_order',
  master_relations: 'sort_order',
};

function quoteLiteral(v: unknown): string {
  if (v === null || v === undefined) return 'null';
  if (typeof v === 'number' || typeof v === 'boolean') return JSON.stringify(v);
  if (v instanceof Date) return JSON.stringify(v.toISOString());
  if (typeof v === 'object') {
    // jsonb columns come back as parsed objects/arrays
    return JSON.stringify(v);
  }
  return JSON.stringify(String(v));
}

async function run(): Promise<void> {
  const url = process.env.DATABASE_URL;
  if (!url) {
    throw new Error('DATABASE_URL is not set');
  }

  const ds = new DataSource({ type: 'postgres', url, entities: [] });
  await ds.initialize();

  const sections: string[] = [];

  sections.push(`// AUTO-GENERATED by src/database/seeds/dump-master-data.ts`);
  sections.push(`// Snapshot of master data at ${new Date().toISOString()}`);
  sections.push(`// DO NOT edit by hand — rerun \`npm run seed:dump\` after changing data in the DB.`);
  sections.push('');
  sections.push(`/* eslint-disable */`);
  sections.push('');

  for (const table of TABLES) {
    let rows: Array<Record<string, unknown>> = [];
    try {
      // Designations are department-scoped via FK. Embed the parent's
      // code + label so seed-from-snapshot.ts can re-resolve the FK
      // against a different DB where the department UUIDs won't match.
      if (table === 'master_designations') {
        rows = await ds.query(`
          SELECT md.*,
                 dep.code  AS department_code,
                 dep.label AS department_label
          FROM master_designations md
          JOIN master_departments dep ON dep.id = md.department_id
          ORDER BY ${ORDER_BY[table]}
        `);
      } else {
        rows = await ds.query(
          `SELECT * FROM ${table} ORDER BY ${ORDER_BY[table]}`,
        );
      }
    } catch (e) {
      console.warn(
        `Skipping ${table}: ${(e as Error).message}`,
      );
      sections.push(`export const ${camel(table)} = []; // table missing or error`);
      sections.push('');
      continue;
    }

    const lines: string[] = [];
    lines.push(`export const ${camel(table)} = [`);
    for (const row of rows) {
      const entries = Object.entries(row).map(
        ([k, v]) => `    ${k}: ${quoteLiteral(v)}`,
      );
      lines.push(`  {`);
      lines.push(entries.join(',\n') + ',');
      lines.push(`  },`);
    }
    lines.push(`];`);
    sections.push(`// ${table} — ${rows.length} row(s)`);
    sections.push(lines.join('\n'));
    sections.push('');
  }

  const outPath = path.join(
    __dirname,
    'master-data.generated.ts',
  );
  fs.writeFileSync(outPath, sections.join('\n'), 'utf8');
  console.log(`Wrote ${outPath}`);

  await ds.destroy();
}

function camel(snake: string): string {
  return snake.replace(/_([a-z])/g, (_, c: string) => c.toUpperCase());
}

run().catch((e) => {
  console.error('dump-master-data failed:', e);
  process.exit(1);
});
