#!/usr/bin/env node

/**
 * testmo-sync.js
 *
 * Reads a test-cases JSON file (generated by the testmo-test-writer agent)
 * and pushes them to Testmo via the REST API.
 *
 * Usage:
 *   node scripts/testmo-sync.js <path-to-test-cases.json> [--dry-run]
 *
 * Environment variables:
 *   TESTMO_URL   - Testmo instance URL (e.g. https://yourteam.testmo.net)
 *   TESTMO_TOKEN - API bearer token (generate from User Profile > API access)
 *   TESTMO_PROJECT_ID - Target project ID in Testmo
 */

const fs = require('fs');
const path = require('path');

async function main() {
  const args = process.argv.slice(2);
  const dryRun = args.includes('--dry-run');
  const filePath = args.find(a => !a.startsWith('--'));

  if (!filePath) {
    console.error('Usage: node scripts/testmo-sync.js <test-cases.json> [--dry-run]');
    process.exit(1);
  }

  const raw = fs.readFileSync(path.resolve(filePath), 'utf-8');
  const testPlan = JSON.parse(raw);

  if (dryRun) {
    console.log('=== DRY RUN - Test Cases Summary ===\n');
    for (const folder of testPlan.folders) {
      console.log(`Folder: ${folder.name}`);
      for (const tc of folder.cases) {
        console.log(`  - [${tc.name}]`);
        if (tc.steps) {
          tc.steps.forEach((s, i) => console.log(`      Step ${i + 1}: ${s}`));
        }
      }
      console.log();
    }
    console.log(`Total folders: ${testPlan.folders.length}`);
    console.log(`Total cases: ${testPlan.folders.reduce((sum, f) => sum + f.cases.length, 0)}`);
    return;
  }

  // --- Live sync to Testmo ---
  const TESTMO_URL = process.env.TESTMO_URL;
  const TESTMO_TOKEN = process.env.TESTMO_TOKEN;
  const TESTMO_PROJECT_ID = process.env.TESTMO_PROJECT_ID;

  if (!TESTMO_URL || !TESTMO_TOKEN || !TESTMO_PROJECT_ID) {
    console.error('Missing environment variables. Required: TESTMO_URL, TESTMO_TOKEN, TESTMO_PROJECT_ID');
    console.error('Tip: Run with --dry-run to preview without pushing to Testmo.');
    process.exit(1);
  }

  let testmo;
  try {
    testmo = require('@testmo/testmo-api');
  } catch {
    console.error('@testmo/testmo-api not installed. Run: npm install @testmo/testmo-api');
    process.exit(1);
  }

  const client = new testmo.ApiClient();
  client.basePath = TESTMO_URL;
  client.authentications['bearerAuth'].accessToken = TESTMO_TOKEN;

  const foldersApi = new testmo.FoldersApi(client);
  const casesApi = new testmo.RepositoryCasesApi(client);
  const projectId = Number(TESTMO_PROJECT_ID);

  console.log(`Syncing to Testmo project ${projectId} at ${TESTMO_URL}\n`);

  for (const folder of testPlan.folders) {
    // Create folder
    let folderId;
    try {
      const folderPayload = { folders: [{ name: folder.name }] };
      if (folder.parent_folder_id) {
        folderPayload.folders[0].parent_id = folder.parent_folder_id;
      }
      const folderResult = await foldersApi.createFolders(projectId, folderPayload);
      folderId = folderResult.data?.[0]?.id;
      console.log(`Created folder: "${folder.name}" (id: ${folderId})`);
    } catch (err) {
      console.error(`Failed to create folder "${folder.name}":`, err.message || err);
      continue;
    }

    // Bulk create cases in batches of 100
    const cases = folder.cases.map(tc => ({
      name: tc.name,
      folder_id: folderId,
      ...(tc.estimate ? { estimate: tc.estimate } : {}),
      ...(tc.tags ? { tags: tc.tags } : {}),
    }));

    for (let i = 0; i < cases.length; i += 100) {
      const batch = cases.slice(i, i + 100);
      try {
        await casesApi.createCases(projectId, { cases: batch });
        console.log(`  Created ${batch.length} case(s) in "${folder.name}"`);
      } catch (err) {
        console.error(`  Failed to create cases in "${folder.name}":`, err.message || err);
      }
    }
  }

  console.log('\nSync complete.');
}

main().catch(err => {
  console.error('Fatal error:', err);
  process.exit(1);
});
